### ISSUE TITLE
Se pueden mover las llamadas de las funciones bajo prueba al bloque "describe"

### ISSUE THREAD

**Issue by evolentini** [santiagosalamandri/practica_tdd#1]
El bloque `describe` sirve para fijar las condiciones de las pruebas y llamar a la función bajo prueba y los bloques `it` para verificar los resultados. De esa forma evitas duplicar código, por ejemplo este bloque

https://github.com/santiagosalamandri/practica_tdd/blob/17347f8fc4ca15d6344f70abe6f14876f7bb38b7/test/test_list.js#L16-L28

se podría escribir como:

```javascript
    describe("when add one element", function () {
        var list = new List();
        list.add("key", "value");
        it("count returns 1", function () {
            assert.equal(list.count(), 1);
        })
        it("returns the value added", function () {
            key = "key";
            assert.equal(list.find(key), "value");
        })
    })
```

**Comment by santiagosalamandri** [comment]
Corregido en tag [vs_B](https://github.com/santiagosalamandri/practica_tdd/tree/vs_B).
