### ISSUE TITLE
Se debe refactorizar el código para evitar duplicaciones

### ISSUE THREAD

**Issue by evolentini** [santiagosalamandri/practica_tdd#2]
El bucle `for` de esta función

https://github.com/santiagosalamandri/practica_tdd/blob/17347f8fc4ca15d6344f70abe6f14876f7bb38b7/src/list.js#L8-L17

es prácticamente idéntico al bucle `for` de esta otra función

https://github.com/santiagosalamandri/practica_tdd/blob/17347f8fc4ca15d6344f70abe6f14876f7bb38b7/src/list.js#L23-L31

con lo cual deberías definir una función interna que tenga el bucle y usarla en las otras dos funciones. Por ejemplo una función que te devuelva el indice de un elemento, y entonces el `add` usa a esa función para determinar si actualiza o agrega y `find` también la usa pero para determinar si devuelve el valor o NULL

**Comment by santiagosalamandri** [comment]
Corregido en tag [vs_B](https://github.com/santiagosalamandri/practica_tdd/tree/vs_B).

**Comment by evolentini** [comment]
Se corrigió la nota del TP a 10 en función de los cambios realizados.
